require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ReactNativeSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'ReactNativeSampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'NablaVideoCall', git: 'git@github.com:nabla/nabla-ios.git', tag: '1.0.0-alpha16'
  pod 'LiveKit', git: 'git@github.com:livekit/client-sdk-swift.git'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
